### ISSUE TITLE
Fix: Clicking on houseHoldDrawer icon and then pressing back does not work accordingly

### ISSUE THREAD

**Issue by frostymate** [commit-crimes/shelf-life#104]
While in the app, when I am the the householdDrawer screen if I use my phone's native back button to go to previous screen it goes to the sign in screen rather than the overview. Attached bellow is a video of the issue.https://github.com/user-attachments/assets/b7831a50-f275-42de-8cfe-cf4d317bd9d0

**Comment by ElMaestroZ** [comment]
Fix: catch back button action, check if drawerState = open -> close drawer, else normal back button behavior
