### ISSUE TITLE
Improve UI for AddFoodItem Screen so its consistent with Scanner Screen

### ISSUE THREAD

**Issue by frostymate** [commit-crimes/shelf-life#142]
Improve UI for AddFoodItem Screen so its consistent with Scanner Screen:

- Things like error handling that are pop-ups should now be similar to the Scanner.
- Make sure the UI is nice.

**Comment by matvitn** [comment]
this ended up also including refactoring utility functions from scanner to be used in addFoodItem and remaking tests for both utility functions and addFoodItem to test the new functionality (also had to modify M1 end to end to fit new functionality)
