### ISSUE TITLE
Update Recipe creation workflow model

### ISSUE THREAD

**Issue by matvitn** [commit-crimes/shelf-life#176]
- Make a seperate Model for Recipe Generation and Recipe Saving
- Implement Recipe Firestore Model
- Update RecipeViewModel to deal with both models
  - Generating Recipes
  - CRUD operations on Firebase Recipes
- Update all tests (especially RecipeViewModel tests which tested the previously hardcoded recipes)

**Comment by alextheprophecy** [comment]
This PR spanned over sprints 6 and 7.
- was opened in Sprint 6
- wrapped up and merged to main in Sprint 7
