### ISSUE TITLE
Connect Barcode to Product Data Retrieval

### ISSUE THREAD

**Issue by ricardo-perello** [commit-crimes/shelf-life#7]
Description: Use the scanned barcode to retrieve product data from an external source (e.g., Open Food Facts).
	•	Subtasks:
	•	Query the Open Food Facts API using the scanned barcode.
	•	Parse and handle the response from the API (e.g., product name, expiration date, nutritional information).
	•	If no match is found, prompt the user to manually enter the product details.

**Comment by alextheprophecy** [comment]
Task Update:

- Issue #20 implementes the FoodFacts MVVM, allowing you to search [OpenFoodFacts ](https://world.openfoodfacts.org/)data (pre parsed and bundled in a `FoodFacts` object) 
- -> Use`FoodFactsViewModel.searchFoodFacts()` to retrieve data with a barcode number or a string filter
