### ISSUE TITLE
implement logic for adding food items into repository

### ISSUE THREAD

**Issue by matvitn** [commit-crimes/shelf-life#8]
Connect the MVVM for food items and have it so it can be done from the AddFood screen. There is no need to connect it to the food database for now, just do it like how it was for ToDos in B2

**Comment by alextheprophecy** [comment]
View Model and Model for foodItems were implemented in #14 . To clarify, this task concerns linking the AddFood screen to the ListFoodItemsViewModel CRUD operations.

**Comment by frostymate** [comment]
The AddFoodScreen both front end and back end done in [#32].
