### ISSUE TITLE
Update Inventory with Scanned Item

### ISSUE THREAD

**Issue by ricardo-perello** [commit-crimes/shelf-life#9]
Description: Add the scanned item to the user’s inventory, including any retrieved product details.
	•	Subtasks:
	•	Create a data model for inventory items.
	•	Add the scanned item to Firestore, including all relevant details (barcode, product name, expiration date).
	•	Display the newly added item in the user’s inventory view.

**Comment by alextheprophecy** [comment]
Clarifying task:

- task #14 already implemented the FoodItem MVVM
- Use `ListFoodItemsViewModel` CRUD operations to add food item
