### ISSUE TITLE
Test and validate individual Food Item Screens

### ISSUE THREAD

**Issue by alextheprophecy** [commit-crimes/shelf-life#91]
Test and validate individual Food Item Screens 

- Add rigorous testing for the Ui for individual Food Item Screen
- Specially extensively test its integration with the firestore repository

**Comment by frostymate** [comment]
The code and the implementation of the test were done and pushed in #40. Came accros a lot of difficulties when it came with testing hence the large time spent on it.

**Comment by frostymate** [comment]
### IndividualFoodItemScreenTest.kt:

- 
- Tests the display and functionality of the IndividualFoodItemScreen:
- Verifies the correct display of food item details.
- Checks the loading indicator when no food item is selected.
- Ensures navigation actions, such as back button, work correctly.

### FoodItemDetailTest.kt:

- 
- Tests the FoodItemDetails component:
- Validates the correct display of food item attributes like category, location, status, and dates.
